# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.app.v1 import admin_pb2 as admin__pb2


class AdminStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccountByPhone = channel.unary_unary(
                '/admin.service.v1.Admin/GetAccountByPhone',
                request_serializer=admin__pb2.GetAccountByPhoneReq.SerializeToString,
                response_deserializer=admin__pb2.GetAccountByPhoneReply.FromString,
                )
        self.GetAccountByUID = channel.unary_unary(
                '/admin.service.v1.Admin/GetAccountByUID',
                request_serializer=admin__pb2.GetAccountByUIDReq.SerializeToString,
                response_deserializer=admin__pb2.GetAccountByUIDReply.FromString,
                )
        self.ListCompanies = channel.unary_unary(
                '/admin.service.v1.Admin/ListCompanies',
                request_serializer=admin__pb2.ListCompaniesReq.SerializeToString,
                response_deserializer=admin__pb2.ListCompaniesReply.FromString,
                )
        self.ListCompaniesByUIDs = channel.unary_unary(
                '/admin.service.v1.Admin/ListCompaniesByUIDs',
                request_serializer=admin__pb2.ListCompaniesByUidReq.SerializeToString,
                response_deserializer=admin__pb2.ListCompaniesReply.FromString,
                )


class AdminServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAccountByPhone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountByUID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCompanies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCompaniesByUIDs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccountByPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountByPhone,
                    request_deserializer=admin__pb2.GetAccountByPhoneReq.FromString,
                    response_serializer=admin__pb2.GetAccountByPhoneReply.SerializeToString,
            ),
            'GetAccountByUID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountByUID,
                    request_deserializer=admin__pb2.GetAccountByUIDReq.FromString,
                    response_serializer=admin__pb2.GetAccountByUIDReply.SerializeToString,
            ),
            'ListCompanies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCompanies,
                    request_deserializer=admin__pb2.ListCompaniesReq.FromString,
                    response_serializer=admin__pb2.ListCompaniesReply.SerializeToString,
            ),
            'ListCompaniesByUIDs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCompaniesByUIDs,
                    request_deserializer=admin__pb2.ListCompaniesByUidReq.FromString,
                    response_serializer=admin__pb2.ListCompaniesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.service.v1.Admin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Admin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAccountByPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.service.v1.Admin/GetAccountByPhone',
            admin__pb2.GetAccountByPhoneReq.SerializeToString,
            admin__pb2.GetAccountByPhoneReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountByUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.service.v1.Admin/GetAccountByUID',
            admin__pb2.GetAccountByUIDReq.SerializeToString,
            admin__pb2.GetAccountByUIDReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCompanies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.service.v1.Admin/ListCompanies',
            admin__pb2.ListCompaniesReq.SerializeToString,
            admin__pb2.ListCompaniesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCompaniesByUIDs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.service.v1.Admin/ListCompaniesByUIDs',
            admin__pb2.ListCompaniesByUidReq.SerializeToString,
            admin__pb2.ListCompaniesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
